config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#login', as: 'login'
  get 'logout', to: 'sessions#logout', as: 'logout'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root 'list_items#index'

  resources :list_items, except: [:new, :edit, :show] do
    member do
      patch 'switch_done', as: 'switch_done'
    end
  end

  resources :users, only: [:create] do
    collection do
      post 'check_login', as: 'check_login'
    end
  end
  get 'register', to: 'users#register', as: 'registration'

end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  validates_presence_of :text

  default_scope{ order(created_at: :desc) }

  def switch_done
    self.done = !self.done
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :login, presence: true,
                    uniqueness: {:case_sensitive => false},
                    length: {maximum: 30},
                    format: /\A\w+\z/
  validates :password, length: {minimum: 7}

  before_save { login.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: [:switch_done, :update, :destroy]

  # GET /list_items (or GET /)
  def index
    @list_items = ListItem.all
    @new_item = ListItem.new
  end

  # POST /list_items
  def create
    @list_item = ListItem.new(list_item_params)
    if @list_item.save
      respond_to do |format|
        format.js
      end
    else
      render nothing: true
    end
  end

  # PATCH /switch_done
  def switch_done
    @list_item.switch_done
    @list_item.save
    respond_to do |format|
      format.js
    end
  end

  # PATCH /list_items/:id
  def update
    @list_item.update(list_item_params)
    render nothing: true
  end

  # DELETE /list_items/:id
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def set_list_item
    @list_item = ListItem.find(params[:id])
  rescue => e
    logger.error("ERROR: #{e.message}")
    render nothing: true
  end

  def list_item_params
    params.require(:list_item).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def logout
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def register
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id

      redirect_to root_path, notice: "Пользователь #{@user.login.capitalize} создан успешно"
    else
      render :register
    end
  end

  def check_login
    @user = User.find_by(login: params[:login].downcase)
    if @user
      render 'check_login', layout: false
    else
      render text: ''
    end
  end

  private

  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation)
  rescue ActionController::ParameterMissing
    {login: '', password: '', password_confirmation: ''}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper

  def list_item_div(list_item)
    classes = ['list_item_div']
    attributes = ["spellcheck='false'"]
    
    if list_item.done?
      classes << 'done'
    else
      attributes << "contenteditable='true'"
    end

    "<div class='#{classes.join(' ')}' #{attributes.join(' ')}>#{list_item.text}</div>"
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def field_errors_tr(model, field)
    "<tr class='errors_tr'>
      <td id='#{field.to_s}_errors'>
        #{field_errors(model, field)}
      </td>
      <td></td>
    </tr>".html_safe
  end

  def field_errors(model, field)
    messages_string(model,field).html_safe
  end

  private

  def messages_string model, field
    if model.errors.added?(field, :blank)
      model.errors.messages[field] = [error_message(:blank, model, field)]
    end

    model.errors.messages[field].map{|msg| "<p>#{msg}</p>" }.join
  end

  def error_message(type, model, field)
    model_name = model.class.to_s.downcase
    msg = I18n.t("activerecord.errors.models.#{model_name}.attributes.#{field.to_s}.#{type.to_s}")
    attr_name = I18n.t("activerecord.attributes.#{model_name}.#{field.to_s}")

    msg.gsub('%{attribute}', attr_name) if msg !~ /\Atranslation missing:/
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lister</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset='utf-8'>
</head>
<body>

<div id='messages'>
  <% if flash[:notice] %>
    <div id='notice'><%= flash[:notice] %></div>
  <% end %>
</div>

<div id='wrapper'>
  <%= yield %>
</div>

</body>
</html>

app/views/list_items/_form.html.erb
<%= form_for @new_item, remote: true do |f| %>
  <%= f.text_area :text, resize: false %>
  <div id='add_button_wrapper'>
    <%= f.submit '' %>
  </div>
<% end %>

app/views/list_items/_list_item.html.erb
<li id="list_item_<%= list_item.id %>" class='list_item'>

  <%= form_for list_item, method: :patch, remote: true do |f| %>
    <%= f.hidden_field :text, value: list_item.text %>

    <%= raw list_item_div(list_item) %>
  <% end %>

  <div class='controls'>
    <%= link_to '', switch_done_list_item_path(list_item), method: :patch, remote: true, class: 'icon check' %>
    <%= link_to '', list_item, method: :delete, remote: true, class: 'icon cross' %>
  </div>
</li>

app/views/list_items/create.js.erb
$('#new_list_item input[type=text]').val('').focus()

list_item = $('<%= escape_javascript(render @list_item) %>')

$('#new_list_item').after(list_item)

app/views/list_items/destroy.js.erb
$('#list_items #list_item_<%= @list_item.id %>').remove()

app/views/list_items/index.html.erb
<aside id='main_controls'>
  <div id='user_menu'>
    <%= render 'shared/user_menu' %>
  </div>
</aside>

<section id='main'>
  <%= render 'form' %>

  <h1>Список</h1>
  <ul id='list_items'>
    
    <div class='clear_fix'></div>
      <%= render partial: 'list_item', collection: @list_items %>
  </ul>
</section>

app/views/list_items/switch_done.js.erb
div = $('#edit_list_item_<%= @list_item.id %> .list_item_div')
<% if @list_item.done? %>  
  div.addClass('done')
  div.attr('contenteditable', false)
<% else %>
  div.removeClass('done')
  div.attr('contenteditable', true)
<% end %>

app/views/shared/_login_form.html.erb
<%= form_tag login_path, method: :post, id: 'login_form' do |f| %>
  <%= text_field_tag 'login', nil, placeholder: 'Логин', id: 'login' %>
  <%= text_field_tag 'password', nil, placeholder: 'Пароль', id: 'password' %>
  <%= submit_tag 'Вход', class: 'button button-narrow button-controls', id: 'log_in' %>
<% end %>

app/views/shared/_user_menu.html.erb
<div id='user_menu_content'>
  <% if @current_user %>
    <span><%= @current_user.login.capitalize %></span>
  <% else %>
    <%= render 'shared/login_form' %>
    <%= link_to 'Регистрация', registration_path, id: 'start_registration' %>
  <% end %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <% content_for :errors do %>
    <% @user.errors.full_messages.each do |e| %>
      <span><%= e %></span>
    <% end %>
  <% end %>
<% end %>

<%= form_for @user, method: :post, html: {class: 'rounded'} do |f| %>
  

  <table>
    <caption>
      <h2>Регистрация</h2>
    </caption>

    <tbody>
      <tr>
        <td id='login_td'>
          <%= f.text_field :login, placeholder: 'Логин', id: 'login', class: 'rounded' %>
        </td>
        <td class='field_hints'>
          <p>*Может содержать латинские буквы, цифры и символ _</p>
        </td>
      </tr>

      <%= field_errors_tr(@user, :login) %>

      <tr>
        <td id='password_td'>
          <%= f.password_field :password, placeholder: 'Пароль', id: 'password', class: 'rounded' %>
        </td>
        <td class='field_hints'>
          <p>**Не менее 7 символов</p>
        </td>
      </tr>

      <%= field_errors_tr(@user, :password) %>

      <tr>
        <td id='password_conf_td'>
          <%= f.password_field :password_confirmation, placeholder: 'Подтверждение', id: 'password_confirmation', class: 'rounded' %>
        </td>
        <td class='field_hints'></td>
      </tr>

      <%= field_errors_tr(@user, :password_confirmation) %>

      <tr>
        <td><%= f.submit 'Зарегистрироваться', id: 'register', class: 'button button-controls rounded' %></td>
        <td></td>
      </tr>
    </tbody>

  </table>

<% end %>

app/views/users/_registration_form.html.erb
<%= form_for @user, method: :post, html: {class: 'rounded'} do |f| %>

  <table>
    <caption>
      <h2>Регистрация</h2>
    </caption>

    <tbody>
      <tr>
        <td id='login_td'>
          <%= f.text_field :login, placeholder: 'Логин', id: 'login', class: 'rounded' %>
        </td>
        <td class='field_hints'>
          <p>*Может содержать латинские буквы, цифры и символ _</p>
        </td>
      </tr>

      <%= field_errors_tr(@user, :login) %>

      <tr>
        <td id='password_td'>
          <%= f.password_field :password, placeholder: 'Пароль', id: 'password', class: 'rounded' %>
        </td>
        <td class='field_hints'>
          <p>**Не менее 7 символов</p>
        </td>
      </tr>

      <%= field_errors_tr(@user, :password) %>

      <tr>
        <td id='password_conf_td'>
          <%= f.password_field :password_confirmation, placeholder: 'Подтверждение', id: 'password_confirmation', class: 'rounded' %>
        </td>
        <td class='field_hints'></td>
      </tr>

      <%= field_errors_tr(@user, :password_confirmation) %>

      <tr>
        <td><%= f.submit 'Зарегистрироваться', id: 'register', class: 'button button-controls rounded' %></td>
        <td></td>
      </tr>
    </tbody>

  </table>

<% end %>

app/views/users/check_login.html.erb
<%= error_message(:taken, @user, :login) %>

app/views/users/register.html.erb
<div id='registration_form_wrapper'>
  <%= render 'registration_form' %>
</div>
<%= link_to "<< Назад", root_path, class: 'button button-controls button-medium rounded', id: 'back' %>